version: '3.8'

# networks:
#   shared-network:
#     driver: bridge

services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb-goodkarma
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_DATABASE=goodkarma
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - shared-network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-goodkarma
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # networks:
    #   - shared-network

  user-service:
    build: 
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "50051:50051"
    # networks:
    #   - shared-network
    depends_on:
      # - mongodb
      - rabbitmq
    env_file:
      - ./user-service/.env

  donation-service:
    build: 
      context: .
      dockerfile: ./donation-service/Dockerfile
    container_name: donation-service
    restart: always
    ports:
      - "50052:50052"
    # networks:
    #   - shared-network
    # depends_on:
    #   - mongodb
    env_file:
      - ./donation-service/.env

  payment-service:
    build: 
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: payment-service
    restart: always
    ports:
      - "50053:50053"
    # networks:
    #   - shared-network
    # depends_on:
    #   - mongodb
    env_file:
      - ./payment-service/.env

  notification-service:
    build: 
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    restart: always
    ports:
      - "50054:50054"
    # networks:
    #   - shared-network
    depends_on:
      # - mongodb
      - rabbitmq
    env_file:
      - ./notification-service/.env

  event-service:
    build: 
      context: .
      dockerfile: ./event-service/Dockerfile
    container_name: event-service
    restart: always
    ports:
      - "50055:50055"
    # networks:
    #   - shared-network
    env_file:
      - ./event-service/.env

  gateway-service:
    build: 
      context: .
      dockerfile: ./gateway-service/Dockerfile
    container_name: gateway-service
    restart: always
    # environment:
    #   - USER_SERVICE_URL=user-service:50051
    #   - DONATION_SERVICE_URL=donation-service:50052
    #   - PAYMENT_SERVICE_URL=payment-service:50053
    #   - NOTIFICATION_SERVICE_URL=notification-service:50054
    #   - EVENT_SERVICE_URL=event-service:50055
    ports:
      - "8080:8080"
    # networks:
    #   - shared-network
    depends_on:
      - user-service
      - donation-service
      - payment-service
      - notification-service
      - event-service
    env_file:
      - ./gateway-service/.env

volumes:
  # mongodb_data:
  rabbitmq_data: