version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-goodkarma
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  user-service:
    build: 
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq
    env_file:
      - ./user-service/.env

  donation-service:
    build: 
      context: .
      dockerfile: ./donation-service/Dockerfile
    container_name: donation-service
    restart: always
    ports:
      - "50052:50052"
    env_file:
      - ./donation-service/.env

  payment-service:
    build: 
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: payment-service
    restart: always
    ports:
      - "50053:50053"
    env_file:
      - ./payment-service/.env

  notification-service:
    build: 
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    restart: always
    ports:
      - "50054:50054"
    # networks:
    #   - shared-network
    depends_on:
      # - mongodb
      - rabbitmq
    env_file:
      - ./notification-service/.env

  event-service:
    build: 
      context: .
      dockerfile: ./event-service/Dockerfile
    container_name: event-service
    restart: always
    ports:
      - "50055:50055"
    env_file:
      - ./event-service/.env

  karma-service:
    build: 
      context: .
      dockerfile: ./karma-service/Dockerfile
    container_name: karma-service
    restart: always
    ports:
      - "50056:50056"
    env_file:
      - ./karma-service/.env

  gateway-service:
    build: 
      context: .
      dockerfile: ./gateway-service/Dockerfile
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - donation-service
      - payment-service
      - notification-service
      - event-service
    env_file:
      - ./gateway-service/.env

volumes:
  rabbitmq_data: