// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/karma.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KarmaService_CreateKarma_FullMethodName = "/karma.KarmaService/CreateKarma"
)

// KarmaServiceClient is the client API for KarmaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KarmaServiceClient interface {
	CreateKarma(ctx context.Context, in *CreateKarmaRequest, opts ...grpc.CallOption) (*CreateKarmaResponse, error)
}

type karmaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKarmaServiceClient(cc grpc.ClientConnInterface) KarmaServiceClient {
	return &karmaServiceClient{cc}
}

func (c *karmaServiceClient) CreateKarma(ctx context.Context, in *CreateKarmaRequest, opts ...grpc.CallOption) (*CreateKarmaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKarmaResponse)
	err := c.cc.Invoke(ctx, KarmaService_CreateKarma_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KarmaServiceServer is the server API for KarmaService service.
// All implementations must embed UnimplementedKarmaServiceServer
// for forward compatibility.
type KarmaServiceServer interface {
	CreateKarma(context.Context, *CreateKarmaRequest) (*CreateKarmaResponse, error)
	mustEmbedUnimplementedKarmaServiceServer()
}

// UnimplementedKarmaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKarmaServiceServer struct{}

func (UnimplementedKarmaServiceServer) CreateKarma(context.Context, *CreateKarmaRequest) (*CreateKarmaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKarma not implemented")
}
func (UnimplementedKarmaServiceServer) mustEmbedUnimplementedKarmaServiceServer() {}
func (UnimplementedKarmaServiceServer) testEmbeddedByValue()                      {}

// UnsafeKarmaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KarmaServiceServer will
// result in compilation errors.
type UnsafeKarmaServiceServer interface {
	mustEmbedUnimplementedKarmaServiceServer()
}

func RegisterKarmaServiceServer(s grpc.ServiceRegistrar, srv KarmaServiceServer) {
	// If the following call pancis, it indicates UnimplementedKarmaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KarmaService_ServiceDesc, srv)
}

func _KarmaService_CreateKarma_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKarmaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KarmaServiceServer).CreateKarma(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KarmaService_CreateKarma_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KarmaServiceServer).CreateKarma(ctx, req.(*CreateKarmaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KarmaService_ServiceDesc is the grpc.ServiceDesc for KarmaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KarmaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "karma.KarmaService",
	HandlerType: (*KarmaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKarma",
			Handler:    _KarmaService_CreateKarma_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/karma.proto",
}
