// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: proto/karma.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateKarmaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKarmaRequest) Reset() {
	*x = CreateKarmaRequest{}
	mi := &file_proto_karma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKarmaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKarmaRequest) ProtoMessage() {}

func (x *CreateKarmaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKarmaRequest.ProtoReflect.Descriptor instead.
func (*CreateKarmaRequest) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKarmaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateKarmaRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateKarmaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKarmaResponse) Reset() {
	*x = CreateKarmaResponse{}
	mi := &file_proto_karma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKarmaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKarmaResponse) ProtoMessage() {}

func (x *CreateKarmaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKarmaResponse.ProtoReflect.Descriptor instead.
func (*CreateKarmaResponse) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKarmaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateKarmaResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateKarmaResponse) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetUserByReferralCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode  string                 `protobuf:"bytes,1,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByReferralCodeRequest) Reset() {
	*x = GetUserByReferralCodeRequest{}
	mi := &file_proto_karma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByReferralCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByReferralCodeRequest) ProtoMessage() {}

func (x *GetUserByReferralCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByReferralCodeRequest.ProtoReflect.Descriptor instead.
func (*GetUserByReferralCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByReferralCodeRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type GetUserByReferralCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByReferralCodeResponse) Reset() {
	*x = GetUserByReferralCodeResponse{}
	mi := &file_proto_karma_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByReferralCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByReferralCodeResponse) ProtoMessage() {}

func (x *GetUserByReferralCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByReferralCodeResponse.ProtoReflect.Descriptor instead.
func (*GetUserByReferralCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByReferralCodeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetReferralCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode  string                 `protobuf:"bytes,1,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralCountRequest) Reset() {
	*x = GetReferralCountRequest{}
	mi := &file_proto_karma_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralCountRequest) ProtoMessage() {}

func (x *GetReferralCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralCountRequest.ProtoReflect.Descriptor instead.
func (*GetReferralCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{4}
}

func (x *GetReferralCountRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type GetReferralCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralCountResponse) Reset() {
	*x = GetReferralCountResponse{}
	mi := &file_proto_karma_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralCountResponse) ProtoMessage() {}

func (x *GetReferralCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralCountResponse.ProtoReflect.Descriptor instead.
func (*GetReferralCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{5}
}

func (x *GetReferralCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateReferralLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,2,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReferralLogRequest) Reset() {
	*x = CreateReferralLogRequest{}
	mi := &file_proto_karma_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReferralLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReferralLogRequest) ProtoMessage() {}

func (x *CreateReferralLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReferralLogRequest.ProtoReflect.Descriptor instead.
func (*CreateReferralLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReferralLogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReferralLogRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type UpdateKarmaAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKarmaAmountRequest) Reset() {
	*x = UpdateKarmaAmountRequest{}
	mi := &file_proto_karma_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKarmaAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKarmaAmountRequest) ProtoMessage() {}

func (x *UpdateKarmaAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKarmaAmountRequest.ProtoReflect.Descriptor instead.
func (*UpdateKarmaAmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateKarmaAmountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateKarmaAmountRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ExchangeRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KarmaRewardId string                 `protobuf:"bytes,2,opt,name=karma_reward_id,json=karmaRewardId,proto3" json:"karma_reward_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRewardRequest) Reset() {
	*x = ExchangeRewardRequest{}
	mi := &file_proto_karma_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRewardRequest) ProtoMessage() {}

func (x *ExchangeRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRewardRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRewardRequest) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{8}
}

func (x *ExchangeRewardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExchangeRewardRequest) GetKarmaRewardId() string {
	if x != nil {
		return x.KarmaRewardId
	}
	return ""
}

type KarmaReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KarmaReward) Reset() {
	*x = KarmaReward{}
	mi := &file_proto_karma_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KarmaReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarmaReward) ProtoMessage() {}

func (x *KarmaReward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarmaReward.ProtoReflect.Descriptor instead.
func (*KarmaReward) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{9}
}

func (x *KarmaReward) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KarmaReward) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KarmaReward) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *KarmaReward) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetKarmaRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rewards       []*KarmaReward         `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKarmaRewardResponse) Reset() {
	*x = GetKarmaRewardResponse{}
	mi := &file_proto_karma_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKarmaRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKarmaRewardResponse) ProtoMessage() {}

func (x *GetKarmaRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKarmaRewardResponse.ProtoReflect.Descriptor instead.
func (*GetKarmaRewardResponse) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{10}
}

func (x *GetKarmaRewardResponse) GetRewards() []*KarmaReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_karma_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_karma_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_karma_proto_rawDescGZIP(), []int{11}
}

var File_proto_karma_proto protoreflect.FileDescriptor

var file_proto_karma_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x22, 0x45, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x56, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x61, 0x72, 0x6d, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x72, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x38,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x58, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x4b, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x61,
	0x72, 0x6d, 0x61, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x58, 0x0a, 0x15, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6b, 0x61,
	0x72, 0x6d, 0x61, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x0b, 0x4b,
	0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4b,
	0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x4b, 0x61, 0x72, 0x6d,
	0x61, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x92, 0x04, 0x0a, 0x0c, 0x4b, 0x61,
	0x72, 0x6d, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x12, 0x19, 0x2e, 0x6b, 0x61, 0x72, 0x6d,
	0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x53, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x12, 0x1f, 0x2e, 0x6b, 0x61, 0x72,
	0x6d, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61,
	0x6c, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6b, 0x61,
	0x72, 0x6d, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x42, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f,
	0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x61, 0x72,
	0x6d, 0x61, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0c, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x62, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72,
	0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6b, 0x61,
	0x72, 0x6d, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x45, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x0c, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1d, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x61, 0x72, 0x6d, 0x61,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_karma_proto_rawDescOnce sync.Once
	file_proto_karma_proto_rawDescData = file_proto_karma_proto_rawDesc
)

func file_proto_karma_proto_rawDescGZIP() []byte {
	file_proto_karma_proto_rawDescOnce.Do(func() {
		file_proto_karma_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_karma_proto_rawDescData)
	})
	return file_proto_karma_proto_rawDescData
}

var file_proto_karma_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_karma_proto_goTypes = []any{
	(*CreateKarmaRequest)(nil),            // 0: karma.CreateKarmaRequest
	(*CreateKarmaResponse)(nil),           // 1: karma.CreateKarmaResponse
	(*GetUserByReferralCodeRequest)(nil),  // 2: karma.GetUserByReferralCodeRequest
	(*GetUserByReferralCodeResponse)(nil), // 3: karma.GetUserByReferralCodeResponse
	(*GetReferralCountRequest)(nil),       // 4: karma.GetReferralCountRequest
	(*GetReferralCountResponse)(nil),      // 5: karma.GetReferralCountResponse
	(*CreateReferralLogRequest)(nil),      // 6: karma.CreateReferralLogRequest
	(*UpdateKarmaAmountRequest)(nil),      // 7: karma.UpdateKarmaAmountRequest
	(*ExchangeRewardRequest)(nil),         // 8: karma.ExchangeRewardRequest
	(*KarmaReward)(nil),                   // 9: karma.KarmaReward
	(*GetKarmaRewardResponse)(nil),        // 10: karma.GetKarmaRewardResponse
	(*Empty)(nil),                         // 11: karma.Empty
}
var file_proto_karma_proto_depIdxs = []int32{
	9,  // 0: karma.GetKarmaRewardResponse.rewards:type_name -> karma.KarmaReward
	0,  // 1: karma.KarmaService.CreateKarma:input_type -> karma.CreateKarmaRequest
	4,  // 2: karma.KarmaService.GetReferralCount:input_type -> karma.GetReferralCountRequest
	6,  // 3: karma.KarmaService.CreateReferralLog:input_type -> karma.CreateReferralLogRequest
	7,  // 4: karma.KarmaService.UpdateKarmaAmount:input_type -> karma.UpdateKarmaAmountRequest
	2,  // 5: karma.KarmaService.GetUserByReferralCode:input_type -> karma.GetUserByReferralCodeRequest
	8,  // 6: karma.KarmaService.ExchangeReward:input_type -> karma.ExchangeRewardRequest
	11, // 7: karma.KarmaService.GetKarmaReward:input_type -> karma.Empty
	1,  // 8: karma.KarmaService.CreateKarma:output_type -> karma.CreateKarmaResponse
	5,  // 9: karma.KarmaService.GetReferralCount:output_type -> karma.GetReferralCountResponse
	11, // 10: karma.KarmaService.CreateReferralLog:output_type -> karma.Empty
	11, // 11: karma.KarmaService.UpdateKarmaAmount:output_type -> karma.Empty
	3,  // 12: karma.KarmaService.GetUserByReferralCode:output_type -> karma.GetUserByReferralCodeResponse
	11, // 13: karma.KarmaService.ExchangeReward:output_type -> karma.Empty
	10, // 14: karma.KarmaService.GetKarmaReward:output_type -> karma.GetKarmaRewardResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_karma_proto_init() }
func file_proto_karma_proto_init() {
	if File_proto_karma_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_karma_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_karma_proto_goTypes,
		DependencyIndexes: file_proto_karma_proto_depIdxs,
		MessageInfos:      file_proto_karma_proto_msgTypes,
	}.Build()
	File_proto_karma_proto = out.File
	file_proto_karma_proto_rawDesc = nil
	file_proto_karma_proto_goTypes = nil
	file_proto_karma_proto_depIdxs = nil
}
